### ISSUE TITLE
"Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by tdserapio** [SNvMK/snvmdb#1]
Hello, so I ran your code from the MD file that is displayed at the front of this GitHub Repository. It is saying: 
`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    db = Database('file.json')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/snvmdb/snvmdb.py", line 17, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/snvmdb/snvmdb.py", line 29, in load
    self.db = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

That is all

**Comment by SNvMK** [comment]
If you provide file name in class constructor, try to just re run your
code, as dumb it can be

пт, 19 февр. 2021 г., 14:28 tdserapio <notifications@github.com>:

**Comment by SNvMK** [comment]
Also I am very excited that someone find my library lol

**Comment by SNvMK** [comment]
Fixed in new release!
